# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Iterative
longtitle: Iterative by Joe Mahoney
email: jmahoney@iterative.co.nz
description: >- # this means to ignore newlines until "baseurl:"
  I'm Joe Mahoney. I'm <a href="https://www.co-operativebank.co.nz">software engineering manager</a>, <a href="https://www.titahibayslsc.org.nz/">surf life guard</a>, and runner from Wellington, New Zealand.<br>I mainly write about and curate links covering software engineering and management, career growth, continuous improvement, creativity, and productivity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iterative.co.nz" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username: jmahoney

permalink: /:title

timezone: Pacific/Auckland

# Site navigation - each item must have a title and a url.
navigation:
  - text: Home
    url: /
  - text: Archive
    url: /archive
  - text: Engineering Manager's Bookshelf
    url: /engineering-manager-bookshelf
  - text: About
    url: /about/
  - text: TV
    url: /tv
  - text: Feed
    url: /feed.xml

# Colors
accent_color: "#e76f51"

# Site footer
footer:
  content: "&copy; Joe Mahoney. All rights reserved."
  has_social: true

# Build settings
remote_theme: jmahoney/pot-kettle-black
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

paginate: 5
paginate_path: "/page:num/"

# Favicon
favicon: images/favicon.png

# Google Analytics id, e.g. "UA-NNNNNNNN-N"
google_analytics: "G-S0Z26TE7Z5"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
exclude:
  - scripts/
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
