name: trigger-rebuild

on:
  schedule:
    - cron:  '7 * * * *'

jobs:
  trigger-rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.3
        with:
          token: ${{ secrets.USER_TOKEN }}
